---
originRequest:
  originServerName: external.joshporter.me

ingress:
  - hostname: joshporter.me
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.joshporter.me"
    service: *svc
  - service: http_status:404
