---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: joshporter-me
spec:
  secretName: joshporter-me-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: joshporter.me
  dnsNames: ["joshporter.me", "*.joshporter.me"]
